
language: node_js
sudo: false
git:
  depth: 1
cache:
  directories:
    - $HOME/.npm
    - node_modules
matrix:
  include:
    - node_js: '8'
      script: npm run lint
      env: CI=pretest
    - node_js: '8'
      script: npm test -- --runInBand
      env: CI=tests 8
    - node_js: '6'
      script: npm test -- --runInBand
      env: CI=tests 6
    - node_js: '4'
      script: npm test -- --runInBand
      env: CI=tests 4
      sudo: required
before_install:
- npm install -g npm@latest
